export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Wrapper } from "./Wrapper/Wrapper";
export { default as Background } from "./Background/Background";
export { default as CompareContainer } from "./CompareContainer/CompareContainer";
export { default as Info } from "./Info/Info";
export { default as Loader } from "./Loader/Loader";
export { default as Login } from "./Login/Login";
export { default as PokemonContainer } from "./PokemonContainer/PokemonContainer";
